---
title: "Liverpool League Comparison"
author: "Ryan Estrellado"
date: "12/26/2018"
output: github_document
---

```{r warning=FALSE, message=FALSE}
library(tidyverse) 
library(googlesheets)
library(knitr)
```

```{r echo=FALSE}
opts_chunk$set(warning = FALSE)
```

```{r}
# Install `engsoccerdata` from GitHub
# library(devtools)
# install_github('jalapic/engsoccerdata', username = "jalapic")
library(engsoccerdata)
```

```{r}
# Load England data
england <- as.tibble(england)
```

```{r}
# Subset Liverpool results 
lfc_past <- england %>% 
  filter(Season %in% c(2008, 2013, 2018), 
         home == "Liverpool" | visitor == "Liverpool") %>% 
  select(-c(FT, division, tier, totgoal, goaldif)) %>% 
  mutate(points = 0, 
         # Home wins
         points = ifelse(home == "Liverpool" & result == "H", 3, points), 
         # Away wins
         points = ifelse(visitor == "Liverpool" & result == "A", 3, points), 
         # Draws
         points = ifelse(result == "D", 1, points)) 
```

2018-2019 data is updated and stored in a [Google Sheet]("https://docs.google.com/spreadsheets/d/1xLXf6uISIuYE2SOAA267-PBpTlO-11AZrmDJsjq4M_c/edit?usp=sharing") 

```{r}
# Read in 2018-2019 data 
key <- extract_key_from_url("https://docs.google.com/spreadsheets/d/1xLXf6uISIuYE2SOAA267-PBpTlO-11AZrmDJsjq4M_c/edit?usp=sharing") 

lfc_18 <- gs_key(key) %>% 
  gs_read()
```

```{r}

lfc_18 <- lfc_18 %>% 
  mutate(result = "D",
         result = ifelse(home == "Liverpool" & hgoal > vgoal, "H", result), 
         result = ifelse(visitor == "Liverpool" & hgoal < vgoal, "A", result), 
         points = 0, 
         # Home wins
         points = ifelse(home == "Liverpool" & result == "H", 3, points), 
         # Away wins
         points = ifelse(visitor == "Liverpool" & result == "A", 3, points), 
         # Draws
         points = ifelse(result == "D", 1, points)) 
```

```{r combine data}
# Combine all seasons
lfc <- bind_rows(lfc_past, lfc_18) %>% 
  arrange(Date)
```

```{r write data}
# Write dataset. This updates in data.world
write_csv(lfc, "output/lfc_title_challenge.csv")
```

```{r}
# Plot point total across games 
lfc %>% 
  group_by(Season) %>%
  mutate(game = 1:length(Season), 
         cum_points = cumsum(points)) %>%
  ungroup() %>% 
  ggplot(data = ., aes(x = game, y = cum_points, group = as.character(Season))) + 
  geom_freqpoly(stat = "identity", aes(color = as.character(Season)), size = 1) + 
  labs(title = "Comparison of Point Totals", 
       color = "Season", 
       x = "Game", 
       y = "Points")
```

## Compare Goals Scored Across Seasons

```{r}
# Transform dataset 
home_goals <- lfc %>% 
  filter(home == "Liverpool") %>% 
  mutate(home_away = "home") %>% 
  select(Date, Season, oppo = visitor, home_away, goals = hgoal)

away_goals <- lfc %>% 
  filter(visitor == "Liverpool") %>% 
  mutate(home_away = "visitor") %>% 
  select(Date, Season, oppo = home, home_away, goals = vgoal)

# Make combined home and away dataset 
lfc_goals <- bind_rows(home_goals, away_goals) %>% 
  mutate_at(vars(Season, oppo, home_away), funs(as.factor))
```

```{r}
# Model goals per game
model_goals <- lm(goals ~ Season, data = lfc_goals)
summary(model_goals)
```

## Compare Goals Conceded Across Seasons 

```{r}
# Transform dataset 
home_goals_c <- lfc %>% 
  filter(home == "Liverpool") %>% 
  mutate(home_away = "home") %>% 
  select(Date, Season, oppo = visitor, home_away, goals = vgoal)

away_goals_c <- lfc %>% 
  filter(visitor == "Liverpool") %>% 
  mutate(home_away = "visitor") %>% 
  select(Date, Season, oppo = home, home_away, goals = hgoal)

# Make combined home and away dataset 
lfc_goals_c <- bind_rows(home_goals_c, away_goals_c) %>% 
  mutate_at(vars(Season, oppo, home_away), funs(as.factor))
```

```{r}
ggplot(data = lfc_goals, aes(x = Season, y = goals)) + 
  geom_boxplot() + 
  labs(title = "Liverpool FC: Median Goals Scored Per Game", 
       x = "")
```

```{r}
# Model goals per game
model_goals_c <- lm(goals ~ Season, data = lfc_goals_c)
summary(model_goals_c)
```

```{r}
ggplot(data = lfc_goals_c, aes(x = Season, y = goals)) + 
  geom_boxplot() + 
  labs(title = "Liverpool FC: Median Goals Conceded Per Game", 
       x = "")
```

